name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_COMPILE_SDK: 33
      ANDROID_BUILD_TOOLS: 33.0.2
      ANDROID_SDK_TOOLS: 9477386
      NDK_VERSION: 26.2.11394342

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          sudo apt-get --quiet update --yes
          sudo apt-get --quiet install --yes mercurial wget unzip git cmake make m4 g++ pkg-config libssl-dev python3 python-is-python3 python3-distutils python3-venv tcl gyp ninja-build bzip2 libz-dev libffi-dev libsqlite3-dev
          sudo apt-get --quiet install --yes patch autoconf libtool pkg-config ant
          sudo apt-get autoremove --purge
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: >
            platforms;android-${{ env.ANDROID_COMPILE_SDK }}
            platform-tools
            build-tools;${{ env.ANDROID_BUILD_TOOLS }}
            ndk;${{ env.NDK_VERSION }}
      
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          root-reserve-mb: '2048'
          temp-reserve-mb: '1000'
          remove-docker-images: 'true'
          remove-codeql: 'true'
          remove-haskell: 'true'
          remove-dotnet: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print env
        run: |
          env
          echo "*******************"
          pwd
          echo "--------------------"
          df -h

      - name: Clone fdroiddata and build
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export fdroidserver=${PWD}/fdroidserver
          git clone --depth 1 https://gitlab.com/fdroid/fdroidserver.git "${fdroidserver}"
          pip install "${fdroidserver}"
          git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git fdroiddata
          cd fdroiddata
          mkdir -p build/srclib
          hg clone --ssh /bin/false -- https://hg.mozilla.org/releases/mozilla-release build/srclib/MozFennec
          ${fdroidserver}/fdroid build --verbose --no-tarball -s us.spotco.fennec_dos:21270020

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: build/fenix/app/build/outputs/
