name: Tesr Space

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      ANDROID_COMPILE_SDK: 33
      ANDROID_BUILD_TOOLS: 33.0.2
      ANDROID_SDK_TOOLS: 9477386
      NDK_VERSION: 26.2.11394342

    steps:
      - name: before
        run: |
          df -h
      
      - name: Maximize build space
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Install deps
        run: |
          sudo apt update 
          sudo apt install -y procps mercurial git

      - name: Print env
        run: |
          df -h
          echo "*******************"
          pwd
          echo "--------------------"
          hg clone --ssh /bin/false -- https://hg.mozilla.org/releases/mozilla-release ff
          git clone --depth 1 https://gitlab.com/fdroid/fdroiddata.git fdroiddata
          echo "*******************"
          df -h
          
